version: '2'

services:
  notebook-server:
    image: ziff/notebook:latest
    build: .
    ports:
      - 8888:8888
    volumes:
      - ./:/home/jovyan/work
    command: notebook --port=8888 --ip=0.0.0.0
